version: '2'

networks:
  basic:

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports: 
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    networks:
      - basic

  gatekeeper:
    image: keycloak/keycloak-gatekeeper
    container_name: gatekeeper
    ports:
      - 3000:3000
    volumes:
      - ./gatekeeper/config.yml:/etc/keycloak/config.yml
      - ./certs:/etc/keycloak/certs
    entrypoint:
      - /opt/keycloak-gatekeeper
      - --config=/etc/keycloak/config.yml
    networks: 
      - basic

  uscentralbank-gatekeeper:
    image: keycloak/keycloak-gatekeeper
    container_name: uscentralbank-gatekeeper
    ports:
      - 13000:13000
    volumes:
      - ./payment_experiment/uscentralbank_config.yml:/etc/keycloak/config.yml
      - ./certs:/etc/keycloak/certs
    entrypoint:
      - /opt/keycloak-gatekeeper
      - --config=/etc/keycloak/config.yml
    networks: 
      - basic 

  usbank1-gatekeeper:
    image: keycloak/keycloak-gatekeeper
    container_name: usbank1-gatekeeper
    ports:
      - 23000:23000
    volumes:
      - ./payment_experiment/usbank1_config.yml:/etc/keycloak/config.yml
      - ./certs:/etc/keycloak/certs
    entrypoint:
      - /opt/keycloak-gatekeeper
      - --config=/etc/keycloak/config.yml
    networks: 
      - basic