version: '2'

networks:
  basic:

services:
  postgres:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: p@ssw0rd
    networks:
      - basic
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports: 
      - 8080:8080
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=p@ssw0rd
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    volumes:
      - ./gatekeeper/mytheme/:/opt/jboss/keycloak/themes/mytheme/:ro
      - ./gatekeeper/mytheme/:/opt/jboss/keycloak/themes/demotheme/:ro
      - ./gatekeeper/demotheme/email:/opt/jboss/keycloak/themes/demotheme/email:ro
    networks:
      - basic
    depends_on:
      - postgres

  gatekeeper:
    image: keycloak/keycloak-gatekeeper
    container_name: gatekeeper
    ports:
      - 3000:3000
    volumes:
      - ./gatekeeper/config.yml:/etc/keycloak/config.yml
      - ./certs:/etc/keycloak/certs
    entrypoint:
      - /opt/keycloak-gatekeeper
      - --config=/etc/keycloak/config.yml
    networks: 
      - basic

  uscentralbank-gatekeeper:
    image: keycloak/keycloak-gatekeeper
    container_name: uscentralbank-gatekeeper
    ports:
      - 13000:13000
    volumes:
      - ./payment_experiment/uscentralbank_config.yml:/etc/keycloak/config.yml
      - ./certs:/etc/keycloak/certs
    entrypoint:
      - /opt/keycloak-gatekeeper
      - --config=/etc/keycloak/config.yml
    networks: 
      - basic 

  usbank1-gatekeeper:
    image: keycloak/keycloak-gatekeeper
    container_name: usbank1-gatekeeper
    ports:
      - 23000:23000
    volumes:
      - ./payment_experiment/usbank1_config.yml:/etc/keycloak/config.yml
      - ./certs:/etc/keycloak/certs
    entrypoint:
      - /opt/keycloak-gatekeeper
      - --config=/etc/keycloak/config.yml
    networks: 
      - basic